version '3.1'

services:
  blog-strapi-api:
    container_name: blog_strapi_api
    hostname: blog_strapi_api
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: blog-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgresData/postgres/blog_strapi_api:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432